main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-activity', views.add_activity, name='add-activity'),
    path('add-activity-request', views.add_activity_request, name='add-activity-request'),
	path('add-person/<int:activity_id>', views.add_person, name='add-person'),
    path('add-person-request/<int:activity_id>', views.add_person_request, name='add-person-request'),
]

ppwstory6/ppwstory6/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ppwstory6/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

class Activity(models.Model):
	activity_name = models.CharField(max_length=200)
	date = models.DateField()
	time_start = models.TimeField()
	time_end = models.TimeField()
	place = models.CharField(max_length=200)

class Person(models.Model):
	activity = models.ForeignKey(Activity, on_delete=models.CASCADE, default="")
	name = models.CharField(max_length=100)

main/forms.py
from django import forms
from .models import Activity, Person
from django.contrib.admin import widgets     

class DateInput(forms.DateInput):
	input_type = 'date'
	
class TimeInput(forms.TimeInput):
	input_type = 'time'

class AddActivityForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.label_suffix = ""

	class Meta:
		model = Activity
		fields ='__all__'
	
	activity_name = forms.CharField(label="Nama", max_length=200)
	date = forms.DateField(label="Tanggal", widget=DateInput())
	time_start = forms.TimeField(label="Mulai", widget=TimeInput())
	time_end = forms.TimeField(label="Berakhir", widget=TimeInput())
	place = forms.CharField(label="Tempat", max_length=200)
	
class AddPersonForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.label_suffix = ""
	
	class Meta:
		model = Person
		fields = ["name"]
	
	name = forms.CharField(label="Nama Peserta", max_length=200)

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Activity, Person
from .forms import AddActivityForm, AddPersonForm
from datetime import datetime

context = {
	"activity_dict" : None,
	"add_activity_form" : None,
	"owner_form" : None,
	"add_activity_form_is_set" : None,
	"add_person_form" : None,
	"add_person_form_is_set" : None,
	"add_person_form_activity_id" : None
}

def reset_context():
	for key in context.keys():
		if key != "activity_dict":
			context[key] = None

def index(request):
	reset_context()

	activity_list = Activity.objects.all()
	activity_dict = dict()

	for activity in activity_list:
		activity_dict[activity] = Person.objects.filter(activity=activity)
		
	context["activity_dict"] = activity_dict
	
	return render(request, 'main/index.html', context)
	
def add_activity_request(request):
	reset_context()
	
	today = datetime.today()
	add_activity_form = AddActivityForm(initial={'date': today.date, 'time_start': today.time, 'time_end': today.time})
	
	context["add_activity_form"] = add_activity_form
	context["owner_form"] = AddPersonForm()
	context["add_activity_form_is_set"] = True
	
	return render(request, 'main/index.html', context)
	
def add_activity(request):
	add_activity_form = AddActivityForm(request.GET or None)
	owner_name = request.GET["name"]
	
	if request.method == 'GET':
		add_activity_form.save()
		Person.objects.create(activity=add_activity_form.instance, name=owner_name)
	
	return HttpResponseRedirect('/')
	
def add_person_request(request, activity_id):
	reset_context()

	context["add_person_form"] = AddPersonForm()
	context["add_person_form_activity_id"] = activity_id
	context["add_person_form_is_set"] = True
	
	return render(request, 'main/index.html', context)
	
def add_person(request, activity_id):
	owner_name = request.GET["name"]
	context["add_person_form_is_set"] = False
	
	if request.method == 'GET':
		Person.objects.create(activity=Activity.objects.get(id=activity_id), name=owner_name)
	
	return HttpResponseRedirect('/')

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kegiatan</title>
{% endblock meta %}

{% block content %}
<div>
	<div class="app-label-container">
		<div class="app-label">Daftar Kegiatan</div>
	</div>
	<div class="activity-list-container">
		{% for activity, persons in activity_dict.items %}
		<div class="activity-card">
			<div class="activity-detail-container">
				<div class="activity-detail">
					<div class="activity-detail-name">Nama</div>
					<div>{{ activity.activity_name }}</div>
				</div>
				<div class="activity-detail">
					<div class="activity-detail-name">Waktu</div>
					<div>{{ activity.date }}</div>
					<div>{{ activity.time_start }} - {{ activity.time_end }}</div>
				</div>
				<div class="activity-detail">
					<div class="activity-detail-name">Tempat</div>
					<div>{{ activity.place }}</div>
				</div>
				<div class="activity-detail">
					<div class="activity-detail-name">Daftar Peserta</div>
					{% for person in persons %}
					<div class="person-container">
						<div class="diamond-container"><img src="{% static 'img/diamond.svg' %}"></div>
						<div>{{ person.name }}</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<div class="add-person-container">
				{% if add_person_form_is_set %}
					{% if add_person_form_activity_id == activity.id %}
					<form action="{% url 'main:add-person' activity.id %}" method="GET">
						<div class="add-person-form">
							<div>{{ add_person_form.name.label_tag }}</div>
							<div>{{ add_person_form.name }}</div>
							<div><input class="add-person-button" type="submit" value="Tambah"></input></div>
						</div>
					</form>
					{% endif %}
				{% else %}
				<form action="{% url 'main:add-person-request' activity.id %}" method="GET">
					<input class="add-person-button" type="submit" value="Gabung"></input>
				</form>
				{% endif %}
			</div>
		</div>
		{% endfor %}
		<div class="activity-card add-activity-card {% if add_activity_form_is_set %} add-activity-card-form {% endif %}">
			{% if add_activity_form_is_set %}
			<form action="/add-activity" method="GET">
				<div class="add-activity-form">
					{% for field in add_activity_form %}
					<div class="form-field">
						<div>{{ field.label_tag }}</div>
						<div>{{ field }}</div>
					</div>
					{% endfor %}
					<div class="form-field">
						<div>{{ owner_form.name.label_tag }}</div>
						<div>{{ owner_form.name }}</div>
					</div>
					<input type="submit" value="Buat kegiatan">
				</div>
			</form>
			{% else %}
			<form action="/add-activity-request">
				<div class="add-activity">
					<div><input type="image" src="{% static 'img/add_activity_icon.png' %}"></div>
					<div>Buat kegiatan baru</div>
				</div>
			</form>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="icon" href="{% static 'img/app_icon.jpg' %}">
	<!--<a href='https://www.freepik.com/vectors/business'>Business vector created by rawpixel.com - www.freepik.com</a>-->
	{% block meta %}
	{% endblock meta %}
</head>

<body>
	{% block content %}
	{% endblock content %}
</body>

</html>